version: '3.7'

volumes:
  postgres_data:
  redis_data:
  
services:

  db:
    restart: always
    image: postgres:11
    container_name: bd01
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    
  
  redis:
    image: "redis:alpine"
    container_name: br01
    volumes:
      - redis_data:/data
    ports:
      - "6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python /src/manage.py runserver 0.0.0.0:8000
    container_name: bs01
    environment:
      - ENVIRONMENT=development
    
    depends_on:
      - db
    volumes:
      - ./src:/src

    ports:
      - "8000:8000"

  