# Generated by Django 3.1 on 2020-08-15 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_auto_20200728_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_like',
            field=models.ManyToManyField(blank=True, related_name='product_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
