# Generated by Django 3.1 on 2020-08-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200810_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
