# Generated by Django 3.0.8 on 2020-07-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='null', max_length=10),
            preserve_default=False,
        ),
    ]
